### ISSUE TITLE
Consider de-labifying this or adding tests

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ruby-instance-variables#4]
This is the first (only?) non-spec Lab users come across, and have heard confusion from at least one user who expected to have tests for a lab. I think it seems foreign to a student's workflow to open a PR without getting tests to pass. 

@aviflombaum thoughts?

**Comment by AnnJohn** [comment]
Do students need to open a PR though for this lesson? They need to create a file and run it, but don't need to fork or make PRs. I can add more clarity though to those instructions within the Readme.

**Comment by curiositypaths** [comment]
Hi there,

This lesson is now a README.

Thank you!
